### ISSUE TITLE
SendingMessage Crash on publish

### ISSUE THREAD

**Issue by Nonobis** [nwithan8/ntfy-dotnet#2]
Hello,

With version 0.3.0 of nugets, publish 

await _client.Publish("topic", "test",);

crash with an unexpected response OK.

If i remove the nugets and use the source directly and déclare an using on ntfy.Requests for SendingMessage no more error ...

Could you check if your current source is really 0.3.0 on nuget.org ?

Thanks

**Comment by nwithan8** [comment]
What do you mean by "remove the nugets and use the source directly"?

**Comment by Nonobis** [comment]
hello,

if i use directly the nuget on store, i have a crash on the publish message.
Notification is send but an exception is fired (with a ok status).

For trying to debug my error, I have extracted you source and then imported directly the project in my solution for debugging ... and after a namespace change for SendingMessage ... no more error...

it's like the version on nuget.org is not trully the latest on source and there is a wrong exception fired. Maybe a quick fix by yourself witouth updating the version number and updating the nuget ?

**Comment by nwithan8** [comment]
I haven't cut a new release on NuGet in months, there is code in the source here on GitHub that is unreleased. I'll merge in your work and cut a new release.
